#!/bin/bash
#
# datasense        start/stop/status script
#
# chkconfig: - 64 36
# description: The datasense shared health record system
# processname: datasense
# config: /etc/default/datasense
# pidfile: /var/run/datasense/datasense.pid
### BEGIN INIT INFO
# Provides: datasense
# Required-Start: $local_fs $remote_fs $network $named $syslog $time
# Required-Stop: $local_fs $remote_fs $network $named $syslog $time
# Short-Description: start and stop datasense system,
# Description: BDSHR system
### END INIT INFO

export DATASENSE_USER=sharedhealth
export DATASENSE_RUN=/opt/datasense/bin/start.sh
export CUR_USER=`/usr/bin/whoami`

# load configuration
. /etc/default/datasense

create_dirs() {
    if [[ ! -e /var/run/datasense ]]; then
        ln -s /opt/datasense/var /var/run/datasense
    fi

    if [[ ! -e /var/log/datasense ]]; then
        mkdir /var/log/datasense
    fi
}
datasense_pid() {
        echo `ps -fe | grep 'datasense.war' | grep -v grep | tr -s " "|cut -d" " -f2`
}

start(){
    pid=$(datasense_pid)
    if [ -n "$pid" ]
    then
        echo -e "\e[00;31mService datasense is already running (pid: $pid)\e[00m"
    else
        # Start datasense
        create_dirs
        echo -e "\e[00;32mStarting datasense\e[00m"
        if [ `user_exists $DATASENSE_USER` = "1" ]  && [ "$CUR_USER" != "$DATASENSE_USER" ];
        then
                /bin/su $DATASENSE_USER -c $DATASENSE_RUN
        else
                sh $DATASENSE_RUN
        fi
  fi
  return 0
}
status(){
          pid=$(datasense_pid)
          if [ -n "$pid" ]; then echo -e "\e[00;32mService datasense is running with pid: $pid\e[00m"
          else echo -e "\e[00;31mService datasense is not running\e[00m"
          fi
}

stop() {
	echo -e "\e[00;31mTerminating datasense\e[00m"
	kill -9 $(datasense_pid)
}
user_exists(){
        if id -u $1 >/dev/null 2>&1; then
        echo "1"
        else
                echo "0"
        fi
}

case $1 in
	start)
	  start
	;;
	stop)
	  stop
	;;
	restart)
	  stop
	  start
	;;
	status)
		status
	;;
	kill)
		stop
	;;
	*)

	;;
esac
exit 0